# Generated by Django 3.0.4 on 2020-03-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlsortner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=100)),
                ('sort_url', models.CharField(max_length=30)),
                ('no_of_clicks', models.CharField(max_length=30)),
            ],
        ),
    ]
