# Generated by Django 3.0.4 on 2020-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsortner',
            name='full_url',
            field=models.CharField(max_length=1000),
        ),
    ]
